### PR TITLE
pin dj-rest-auth to 4.0.1

### PR DESCRIPTION
**Pull request by akihikokuroda**
### Summary

dj-rest-auth 5.0.0 was released today.  It causes an error at getting token.

### Details and comments

Here is the log of the gateway pod.  
```
ERROR 2023-09-12 00:12:18,829 log.py:241 : Internal Server Error: /dj-rest-auth/keycloak/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/views.py", line 48, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/views.py", line 125, in post
    self.serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/registration/serializers.py", line 94, in validate
    app = adapter.get_provider().app
AttributeError: 'KeycloakProvider' object has no attribute 'app'
```

### CODE REVIEW

**Review by Tansito — CHANGES_REQUESTED** [review]
In fact `4.0.1` should not work either. We have the update to version 4 `on-hold` #626 (I thought we had it pinned). I would pin it to `3.0.0` that it was the last one working from what we know.

**Comment by akihikokuroda** [comment]
@Tansito It was `dj-rest-auth>=3.0.0` so it could pick up the latest version.  The Docker notebook test started failing yesterday and dj-rest-auth 5.0.0 was released about the same time.  We also updated django to 4.2.5 yesterday.   It seems that dj-rest-auth 4.0.1 works fine with django 4.2.5.  The Docker notebook test passes with this combination.  WDYT?

**Comment by Tansito** [comment]
Oh, ok. Let me test it today and I will let you know if I find something 👍

**Review by Tansito — APPROVED** [review]
You are totally right @akihikokuroda , seems v4 is working now and the problem is the v5 now 👍 , let's move this. Thank you, Aki!
